labgrid-leinelab-tplink_tl-wr1043nd-v3:
  location: leinelab
  RawSerialPort:
    port: "/dev/ttyS0"
    speed: 115200
  power:
    cls: SysfsGPIO
    index: 539 # gpio 27
  reset:
    cls: SysfsGPIO
    index: 529 # gpio 17
  TFTPProvider:
    internal: "/srv/tftp/"
    external: "tplink_tl-wr1043nd-v3/"
  NetworkService:
    address: 192.168.1.1
    username: root
